# test:
#   stage: test
#   image: mhart/alpine-node:12
#   script:
#     - yarn
#     - npm run lint
# image: ubuntu:18.04
image: tiangolo/docker-with-compose

# services:
#   - docker
#   - docker:dind

deploy_production:
  stage: deploy
  tags:
    - production
  only:
    refs:
      - tags
      - triggers
      - master
  when: manual
  before_script:
    # - docker info
    # - apk add --no-cache git py-pip gcc
    # - apt-get update
    # - apt-get install -y python-pip \
    #   curl \
    #   apt-transport-https \
    #   ca-certificates \
    #   curl \
    #   gnupg-agent \
    #   software-properties-common
    # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    # - apt-key fingerprint 0EBFCD88
    # - add-apt-repository \
    #   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    #   $(lsb_release -cs) \
    #   stable"
    # - apt-get update
    # - sudo apt-get install docker-ce docker-ce-cli containerd.io
    # - pip install docker-compose
    # - yum install epel-release
    # - yum install python-pip
    - echo APP_URL="$APP_URL" >> .env
    - echo API_URL="$API_URL" >> .env
    - echo GA_TRACKING_ID="$GA_TRACKING_ID" >> .env
    - echo FACEBOOK_PIXEL_ID="$FACEBOOK_PIXEL_ID" >> .env
    - echo SENTRY_DSN="$SENTRY_DSN" >> .env
    - echo DOMAIN="$DOMAIN" >> .env
    - echo GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY" >> .env
    - echo SECRET_IV="$SECRET_IV" >> .env
    - echo SECRET_KEY="$SECRET_KEY" >> .env
    - echo SHOPIFY_URL="$SHOPIFY_URL" >> .env
    - echo SHOPIFY_VARIANT_ID="$SHOPIFY_VARIANT_ID" >> .env
    - echo STOREFRONT_API_KEY="$STOREFRONT_API_KEY" >> .env
    - echo HOST="whenigrowup.co.id" >> .env
    - echo ENVIRONMENT="prd" >> .env
    - cat .env
    # - pip install python-dotenv
  script:
    - source .env
    # - git submodule sync --recursive
    # - git submodule update --init --recursive
    # - cp .env ./allgrownup/.env
    - docker-compose up --build -d
    # - docker-compose up -d
# deploy_staging:
#   stage: deploy
#   tags:
#     - staging
#   when: manual
#   before_script:
#     - echo APP_URL="$APP_URL" >> .env
#     - echo API_URL="$API_URL" >> .env
#     - echo GA_TRACKING_ID="$GA_TRACKING_ID" >> .env
#     - echo FACEBOOK_PIXEL_ID="$FACEBOOK_PIXEL_ID" >> .env
#     - echo SENTRY_DSN="$SENTRY_DSN" >> .env
#     - echo DOMAIN="$DOMAIN" >> .env
#     - echo GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY" >> .env
#     - echo SECRET_IV="$SECRET_IV" >> .env
#     - echo SECRET_KEY="$SECRET_KEY" >> .env
#     - echo SHOPIFY_URL="$SHOPIFY_URL" >> .env
#     - echo SHOPIFY_VARIANT_ID="$SHOPIFY_VARIANT_ID" >> .env
#     - echo STOREFRONT_API_KEY="$STOREFRONT_API_KEY" >> .env
#     - echo HOST="wigu.taufiqelrahman.com" >> .env
#     - echo ENVIRONMENT="stg" >> .env
#     - cat .env
#   script:
#     - source .env
#     - docker-compose up --build -d
